import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import CustomCursor from "@/components/ui/CustomCursor";
import Footer from "./home/_components/Footer";
import { IoLogoWhatsapp } from "react-icons/io5";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <a className="whats-app relative" href="#" target="_blank">
                    <IoLogoWhatsapp className="my-float absolute bottom-4 right-4  " />
                </a>
                <CustomCursor />
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
