import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./home/_components/Footer";
import { IoLogoWhatsapp } from "react-icons/io5";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
            >
                <a
                    href="https://wa.me/919995519522?text=Hi%21%20I%20just%20visited%20your%20website%20and%20I%27m%20interested%20in%20your%20digital%20marketing%20services.%20Can%20you%20tell%20me%20more%3F"
                    className="btn-whatsapp-pulse"
                >
                    <IoLogoWhatsapp />
                </a>

                {/* <CustomCursor /> */}
                {/* <Header /> */}
                {children}
                <Footer />
            </body>
        </html>
    );
}
